version: '3.8'

services:
  db:
    image: postgres:16.1
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '${APP_PORT:-8080}:8080'
    env_file:
      - .env
    tty: true
    networks:
      - default
    volumes:
      - ./:/app
    depends_on:
      - db
